version: 2

models:

    - name: stg_customers
      description: staged customer data for jaffle shop app
      columns: 
        - name: customer_id
          description: primary key for customers
          tests:
            - unique
            - not_null

    - name: stg_orders
      description: staged order data from the jaffle app
      columns:
        - name: order_id
          description: primary key for orders 
        - name: status
          description: "{{ doc('order_status')}}"
          tests:
            - accepted_values:
                values:
                  - completed
                  - shipped
                  - returned
                  - placed
                  - return_pending
    - name: customer_id
      tests:
        - relationships:
            to: ref('stg_customers')
            field: customer_id